# Generated by Django 4.2.7 on 2025-10-09 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('road_worthiness', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('insurance_certificate', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('inside_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('driver_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='users.driverprofile')),
            ],
        ),
    ]
