# Generated by Django 4.2.7 on 2025-10-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_verificationcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verificationcode',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='verificationcode',
            unique_together={('email', 'type')},
        ),
        migrations.RemoveField(
            model_name='verificationcode',
            name='phone_number',
        ),
    ]
