# Generated by Django 4.2.7 on 2025-10-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_verificationcode_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
