# Generated by Django 4.2.7 on 2025-10-14 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_driverprofile_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='license_document',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='selfie',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='back_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='front_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='inside_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_certificate',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='road_worthiness',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('other', 'Other')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
