# Generated by Django 4.2.7 on 2025-10-14 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_driverprofile_license_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('license_document', 'License Document'), ('selfie', 'Selfie'), ('road_worthiness', 'Road Worthiness'), ('insurance_certificate', 'Insurance Certificate'), ('front_image', 'Front Image'), ('back_image', 'Back Image'), ('inside_image', 'Inside Image')], max_length=50)),
                ('file', models.FileField(upload_to='driver_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Document',
                'verbose_name_plural': 'Driver Documents',
                'unique_together': {('user', 'document_type')},
            },
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='license_document',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='selfie',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='back_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='front_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='inside_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_certificate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='road_worthiness',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
