# Generated by Django 4.2.7 on 2025-10-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_driverdocument_remove_driverprofile_license_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='file',
            field=models.TextField(),
        ),
    ]
