# Generated by Django 4.2.7 on 2025-10-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_driverdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='file',
            field=models.FileField(upload_to='driver_documents/%Y/%m/%d/'),
        ),
    ]
