# Generated by Django 4.2.7 on 2025-10-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
