# Generated by Django 4.2.7 on 2025-10-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_driverprofile_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='todays_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
