# Generated by Django 4.2.7 on 2025-10-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_todays_earnings_user_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='manufacturer',
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='document_type',
            field=models.CharField(choices=[('license_document', 'License Document'), ('selfie', 'Selfie'), ('front_image', 'Front Image'), ('back_image', 'Back Image'), ('inside_image', 'Inside Image')], max_length=50),
        ),
    ]
