# Generated by Django 4.2.7 on 2025-10-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='route',
            name='estimated_time',
        ),
    ]
