# Generated by Django 5.1.4 on 2025-11-04 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_route_distance_remove_route_estimated_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_type', models.CharField(choices=[('bus', 'Bus'), ('vehicle', 'Vehicle')], max_length=10)),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('reservation_seats', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('driver_profile_image_url', models.URLField(blank=True, null=True)),
                ('driver_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('driver_trips', models.IntegerField(blank=True, null=True)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_company', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
