# Generated by Django 5.1.4 on 2025-11-04 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.route'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='driver_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
