# Generated by Django 5.1.4 on 2025-11-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_reservation_route_alter_reservation_driver_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='driver_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
