# Generated by Django 5.1.4 on 2025-11-05 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_reservation_driver_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='users.driverprofile'),
        ),
    ]
