# Generated by Django 4.2.7 on 2025-11-06 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('reservation', 'Reservation'), ('system', 'System')], default='reservation', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.driverprofile')),
            ],
        ),
    ]
