# Generated by Django 4.2.7 on 2025-11-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flutterwavesubaccount',
            name='account_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
