# Generated by Django 4.2.7 on 2025-11-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_flutterwavesubaccount_account_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
