# Generated by Django 4.2.7 on 2025-11-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_reservation_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
