# Generated by Django 4.2.7 on 2025-11-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_reservation_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
