# Generated by Django 4.2.7 on 2025-11-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_reservation_tx_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
