# Generated by Django 4.2.7 on 2025-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
