# Generated by Django 4.2.7 on 2025-11-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_notification_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
