from django.urls import path
from .views import DeleteUserView, DisableUserView, EnableUserView, GetMyDriverProfileView, InitiateSignupView, TotalPaidReservationsView, VerifySignupView, LoginView, VerifyLoginView, VerifyDriverSignupWithFilesView, ResendOTPView, UpdateDriverProfileView, UpdateVehicleView, UpdateUserProfileView, UploadUserProfilePictureView, DriverVerificationStatusView, GetDriverVerificationStatusByIdView, GetAdminDriverDocumentsView, GetMyDriverDocumentsView, UserStatsView, ListUsersView, ListDriversView, GetDriverProfileView, RouteListCreateView, RouteDetailView, ReservationListCreateView, ReservationDetailView, SearchRoutesView, CreateFlutterwaveSubaccountView, GetMyFlutterwaveSubaccountView, RequestWithdrawalView, ListMyWithdrawalRequestsView, ListAllWithdrawalRequestsView, ProcessWithdrawalRequestView, DriverReservationsView, CompletedReservationsView, ListNotificationsView, MarkNotificationReadView, FlutterwaveWebhookView, PaymentCallbackView, TotalDriversTodaysEarningsView, DriversTodaysEarningsView, AllReservationsView, ListUserNotificationsView, MarkUserNotificationReadView, UpdateUserLocationView, GetAllUserLocationsView, GetUserLocationView, UpdateUserLocationByIdView


urlpatterns = [
    path('initiate-signup/', InitiateSignupView.as_view(), name='initiate-signup'),
    path('verify-signup/', VerifySignupView.as_view(), name='verify-signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('verify-login/', VerifyLoginView.as_view(), name='verify-login'),
    path('verify-driver-signup-with-files/', VerifyDriverSignupWithFilesView.as_view(), name='verify-driver-signup-with-files'),
    path('resend-otp/', ResendOTPView.as_view(), name='resend-otp'),
    path('update-driver-profile/', UpdateDriverProfileView.as_view(), name='update-driver-profile'),
    path('update-vehicle/', UpdateVehicleView.as_view(), name='update-vehicle'),
    path('update-user-profile/', UpdateUserProfileView.as_view(), name='update-user-profile'),
    path('upload-user-profile-picture/', UploadUserProfilePictureView.as_view(), name='upload-user-profile-picture'),
    path('driver-verification-status/', DriverVerificationStatusView.as_view(), name='driver-verification-status'),
    path('driver-verification-status/<int:user_id>/', GetDriverVerificationStatusByIdView.as_view(), name='driver-verification-status-by-id'),
    path('admin-driver-documents/<int:user_id>/', GetAdminDriverDocumentsView.as_view(), name='admin-driver-documents'),
    path('my-documents/', GetMyDriverDocumentsView.as_view(), name='my-documents'),
    path('user-stats/', UserStatsView.as_view(), name='user-stats'),
    path('list-users/', ListUsersView.as_view(), name='list-users'),
    path('list-drivers/', ListDriversView.as_view(), name='list-drivers'),
    path('drivers/total-todays-earnings/', TotalDriversTodaysEarningsView.as_view(), name='total-drivers-todays-earnings'),
    path('drivers/todays-earnings/', DriversTodaysEarningsView.as_view(), name='drivers-todays-earnings'),
    path('total-paid-reservations/', TotalPaidReservationsView.as_view(), name='total-paid-reservations'),
    path('driver-profile/<int:user_id>/', GetDriverProfileView.as_view(), name='driver-profile'),
    path('my-driver-profile/', GetMyDriverProfileView.as_view(), name='my-driver-profile'),
    path('routes/', RouteListCreateView.as_view(), name='route-list-create'),
    path('routes/<int:pk>/', RouteDetailView.as_view(), name='route-detail'),
    path('reservations/', ReservationListCreateView.as_view(), name='reservation-list-create'),
    path('reservations/<int:pk>/', ReservationDetailView.as_view(), name='reservation-detail'),
    path('search-routes/', SearchRoutesView.as_view(), name='search-routes'),
    path('create-flutterwave-subaccount/', CreateFlutterwaveSubaccountView.as_view(), name='create-flutterwave-subaccount'),
    path('my-flutterwave-subaccount/', GetMyFlutterwaveSubaccountView.as_view(), name='my-flutterwave-subaccount'),
    path('request-withdrawal/', RequestWithdrawalView.as_view(), name='request-withdrawal'),
    path('my-withdrawal-requests/', ListMyWithdrawalRequestsView.as_view(), name='my-withdrawal-requests'),
    path('all-withdrawal-requests/', ListAllWithdrawalRequestsView.as_view(), name='all-withdrawal-requests'),
    path('process-withdrawal/<int:withdrawal_id>/', ProcessWithdrawalRequestView.as_view(), name='process-withdrawal'),
    path('driver-reservations/', DriverReservationsView.as_view(), name='driver-reservations'),
    path('completed-reservations/', CompletedReservationsView.as_view(), name='completed-reservations'),
    path('list-notifications/', ListNotificationsView.as_view(), name='list-notifications'),
    path('mark-notification-read/<int:notification_id>/', MarkNotificationReadView.as_view(), name='mark-notification-read'),
    path('flutterwave-webhook/', FlutterwaveWebhookView.as_view(), name='flutterwave-webhook'),
    path('payment-callback/', PaymentCallbackView.as_view(), name='payment-callback'),
    path('all-reservations/', AllReservationsView.as_view(), name='all-reservations'),
    path('list-user-notifications/', ListUserNotificationsView.as_view(), name='list-user-notifications'),
    path('mark-user-notification-read/<int:notification_id>/', MarkUserNotificationReadView.as_view(), name='mark-user-notification-read'),
    path('disable-user/', DisableUserView.as_view(), name='disable-user'),
    path('enable-user/', EnableUserView.as_view(), name='enable-user'),
    path('delete-user/', DeleteUserView.as_view(), name='delete-user'),
    path('update-user-location/', UpdateUserLocationView.as_view(), name='update-user-location'),
    path('locations/', GetAllUserLocationsView.as_view(), name='user-locations'),
    path('all-user-locations/', GetAllUserLocationsView.as_view(), name='all-user-locations'),
    path('user-location/<int:user_id>/', GetUserLocationView.as_view(), name='get-user-location'),
    path('update-user-location/<int:user_id>/', UpdateUserLocationByIdView.as_view(), name='update-user-location-by-id'),
]
